name: Build and Publish Content On Every master update
on:
  push:
    branches:
      - master
    paths:
      - 'blog/**'
      - 'docs/**'
      - 'src/**'
      - 'static/**'
      - 'docusaurus.config.js'
      - 'sidebars.js'

jobs:
  build:
    name: Build and Publish content
    runs-on: ubuntu-latest
    steps:
      - name: Pull source code
        uses: actions/checkout@v2
        with:
          path: './'
      - name: Detect yarn cache location
        id: yarn_cache
        shell: bash
        run: |
          yarn_cache_dir=`yarn cache dir`
          echo "::set-env name=yarn_cache_dir::$yarn_cache_dir"
      - name: Set up workflow caching for yarn cache
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ env.yarn_cache_dir }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: yarn
      - name: Install subrepo
        run: |
          git clone https://github.com/ingydotnet/git-subrepo ~/git-subrepo
          source ~/git-subrepo/.rc
      - name: Build content
        shell: bash
        run: yarn run build
      - name: Setup git creds
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git config --global user.password ${{ secrets.GITHUB_TOKEN }}
      - name: Push content to gh-pages
        env:
          GIT_USER: "${{ github.GITHUB_ACTOR }}:${{ secrets.GITHUB_TOKEN }}"
        run: yarn run deploy
