name: Build and Publish Content On Every master update
on:
  push:
    branches:
      - master
    paths:
      - 'blog/**'
      - 'docs/**'
      - 'src/**'
      - 'static/**'
      - 'docusaurus.config.js'
      - 'sidebars.js'

jobs:
  build:
    name: Build and Publish content
    runs-on: ubuntu-latest
    steps:
      - name: Pull source code
        uses: actions/checkout@v2
        with:
          path: './'
      - name: Detect yarn cache location
        id: yarn-cache
        shell: bash
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Set up workflow caching for yarn cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-
      - name: Install dependencies
        run: yarn
      - name: Install subrepo
        run: |
          git clone https://github.com/ingydotnet/git-subrepo ~/git-subrepo
          source ~/git-subrepo/.rc
      - name: Setup git creds
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git config --global user.password ${{ secrets.GITHUB_TOKEN }}
          echo "::set-env name=GIT_USER::${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}"
      - name: Push content to gh-pages
        run: yarn run deploy
